const books = [
  {
    BookID: 1,
    ISBN: "0-7475-3269-9",
    BookName: "Harry Potter Book 1",
    Author: "J.K. Rowling",
    Category: "Fantasy",
    price: 10.54,
    description: " It follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry.",
    image: "Images/Book1.jpg",
  },
  {
    BookID: 2,
    ISBN: "9780670824397",
    BookName: "Matilda",
    Author: "Roald Dahl",
    Category: "Children's Literature",
    price: 8.63,
    description: "A story of the girl with extraordinary abilities (Telekinisis power). Matilda is a sweet, lovable and exceptional young girl, but her parents think she’s just a nuisance.",
    image: "Images/Book2.jpg",
  },

  {
    BookID: 3,
    ISBN: "9780749907730",
    BookName: "Duke and I",
    Author: "Julia Quinn",
    Category: "Historical Romance",
    price: 12.99,
    description: "The story of Simon Basset & the lovely Daphne Bridgerton. As Daphne waltzes across ballroom after ballroom with Simon, she soon forgets that their courtship is a complete sham. ",
    image: "Images/Book3.jpg",
  },

  {
    BookID: 4,
    ISBN: "9780062560537",
    BookName: "Chibi Manga",
    Author: "Eva Minguet",
    Category: "Art & Architecture",
    price: 9.75,
    description: "Covers both manga and anime, and includes detailed information on how to apply digital color, 3D designs, vectorial drawing, and a host of other fascinating and useful design applications.",
    image: "Images/Book4.jpg",
  },

  {
    BookID: 5,
    ISBN: "9781087893341",
    BookName: "The After Life",
    Author: "R Craig Hogan",
    Category: "Spirituality & Belief",
    price: 3.99,
    description: "This book challenges the assumptions most of us learned as we grew up. If you follow the evidence keeping an open mind, you will come to the same conclusion a vast body of scientists.",
    image: "Images/Book5.png",
  },

  {
    BookID: 6,
    ISBN: "9780451528834",
    BookName: "The Secret Garden",
    Author: "Frances Hodgson Burnett",
    Category: "Children's Novel",
    price: 2.78,
    description: "Opening the door into the innermost places of the heart, The Secret Garden is a timeless classic that has left generations of readers with warm, lifelong memories of its magical charms.",
    image: "Images/Book6.jpg",
  },

  {
    BookID: 7,
    ISBN: "9780142419304",
    BookName: "Charlie & the Chocolate Factory",
    Author: "Roald Dahl",
    Category: "Children's Folk tales",
    price: 9.99,
    description: "Willy Wonka's famous chocolate factory is opening at last! But only five lucky children will be allowed inside, including our hero Charlie Bucket.",
    image: "Images/Book7.jpg",
  },
  {
    BookID: 8,
    ISBN: "9781503250475",
    BookName: "A Little Princess",
    Author: "Frances Hodgson Burnett",
    Category: "Classic Literature",
    price: 8.55,
    description: "Sara Crewe, a little girl who imagines she's a princess in order to survive hard times alone at Miss Minchins London boarding school. Discover the magic of this beloved story.",
    image: "Images/Book8.jpg",
  },

  {
    BookID: 9,
    ISBN: "9781568363912",
    BookName: "Totto Chan",
    Author: "Tetsuko Kuroyanagi",
    Category: "Japanese Biographies",
    price: 7.95,
    description: "An ideal school in Tokyo during World War II that combined learning with fun, freedom, and love. This unusual school had old railroad cars for classrooms, and it was run by an extraordinary headmaster.",
    image: "Images/Book9.jpg",
  },

  {
    BookID: 10,
    ISBN: "9781760668983",
    BookName: "The Lion King",
    Author: "Justine Korman",
    Category: "Fiction",
    price: 4.35,
    description: "The exciting tale of Simba and Nala, young cubs who earns their place in the Circle of Life. Young prince Simba is the next in line to succeed after his father, Mufasa, to the throne.",
    image: "Images/Book10.jpg",
  },

  {
    BookID: 11,
    ISBN: " 9798712099405",
    BookName: "What Katy Did Next",
    Author: "Susan Coolidge",
    Category: "Novel",
    price: 3.64,
    description: "Opens by reintroducing the Carr family and introduces the widow Mrs. Ashe. who has a nephew, Walter, sent over for a visit and it is discovered that he has scarlet fever. ",
    image: "Images/Book11.jpg",
  },

  {
    BookID: 12,
    ISBN: "9781442478602",
    BookName: "Nancy Drew Diaries Book 5",
    Author: "Carolyn Keene",
    Category: "Mystery",
    price: 5.99,
    description: "At the prestigious River Heights Horse Show, the riders to the owners will do anything to win…even drug the horses! Nancy, Bess and George are on the case!",
    image: "Images/Book12.jpg",
  },
];

export default books;
